apiVersion: v1
kind: ConfigMap
metadata:
  name: classroom-configmap
data:
  # database_url: database-service # https://stackoverflow.com/questions/71020121/
  database_url: jdbc:postgresql://database-service:5432/classroom
