apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
  name: postgres-db
spec:
  replicas:
  selector:
    matchLabels:  
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
      - name: postgres-db
        image: postgres:latest
        ports:
        - protocol: TCP
          containerPort: 1234
        env:
        - name: POSTGRES_DB
          value: "classroom"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-database-secrete
              key: postgres-root-username 
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-database-secrete
              key: postgres-root-password
        
        