apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
  name: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:  
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
      - name: postgres-db
        image: postgres:latest
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
        imagePullPolicy: Never    # To use local image & not to pull from the registry
        ports:
        - protocol: TCP
          containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: classroom
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-database-secrete
              key: postgres-root-username 
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-database-secrete
              key: postgres-root-password
        
        