apiVersion: v1
kind: Service

metadata:
  name: database-service

spec:
  selector: 
    app: postgres-db
    tier: database
  clusterIP: None
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
