// source: hello.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.hello.world.Person');
goog.provide('proto.hello.world.Person.Address');
goog.provide('proto.hello.world.Person.BloodGroup');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.Date');
goog.require('proto.myPackage.DetailedDate');
goog.require('proto.myPackage.TimeStamp');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.hello.world.Person = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.hello.world.Person.repeatedFields_, null);
};
goog.inherits(proto.hello.world.Person, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.hello.world.Person.displayName = 'proto.hello.world.Person';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.hello.world.Person.Address = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.hello.world.Person.Address, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.hello.world.Person.Address.displayName = 'proto.hello.world.Person.Address';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.hello.world.Person.repeatedFields_ = [8];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.hello.world.Person.prototype.toObject = function(opt_includeInstance) {
  return proto.hello.world.Person.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.hello.world.Person} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.hello.world.Person.toObject = function(includeInstance, msg) {
  var f, obj = {
    age: jspb.Message.getFieldWithDefault(msg, 1, 0),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    height: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
    weight: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
    isMarried: jspb.Message.getBooleanFieldWithDefault(msg, 6, false),
    smallProfilePic: msg.getSmallProfilePic_asB64(),
    phoneNumbersList: (f = jspb.Message.getRepeatedField(msg, 8)) == null ? undefined : f,
    bloodGroup: jspb.Message.getFieldWithDefault(msg, 9, 0),
    officeAddress: (f = msg.getOfficeAddress()) && proto.hello.world.Person.Address.toObject(includeInstance, f),
    birthDate: (f = msg.getBirthDate()) && proto.Date.toObject(includeInstance, f),
    birthTime: (f = msg.getBirthTime()) && proto.myPackage.TimeStamp.toObject(includeInstance, f),
    lastLogin: (f = msg.getLastLogin()) && proto.myPackage.DetailedDate.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.hello.world.Person}
 */
proto.hello.world.Person.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.hello.world.Person;
  return proto.hello.world.Person.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.hello.world.Person} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.hello.world.Person}
 */
proto.hello.world.Person.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAge(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setHeight(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setWeight(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsMarried(value);
      break;
    case 7:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setSmallProfilePic(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.addPhoneNumbers(value);
      break;
    case 9:
      var value = /** @type {!proto.hello.world.Person.BloodGroup} */ (reader.readEnum());
      msg.setBloodGroup(value);
      break;
    case 10:
      var value = new proto.hello.world.Person.Address;
      reader.readMessage(value,proto.hello.world.Person.Address.deserializeBinaryFromReader);
      msg.setOfficeAddress(value);
      break;
    case 11:
      var value = new proto.Date;
      reader.readMessage(value,proto.Date.deserializeBinaryFromReader);
      msg.setBirthDate(value);
      break;
    case 12:
      var value = new proto.myPackage.TimeStamp;
      reader.readMessage(value,proto.myPackage.TimeStamp.deserializeBinaryFromReader);
      msg.setBirthTime(value);
      break;
    case 13:
      var value = new proto.myPackage.DetailedDate;
      reader.readMessage(value,proto.myPackage.DetailedDate.deserializeBinaryFromReader);
      msg.setLastLogin(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.hello.world.Person.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.hello.world.Person.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.hello.world.Person} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.hello.world.Person.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAge();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getHeight();
  if (f !== 0.0) {
    writer.writeFloat(
      4,
      f
    );
  }
  f = message.getWeight();
  if (f !== 0.0) {
    writer.writeDouble(
      5,
      f
    );
  }
  f = message.getIsMarried();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getSmallProfilePic_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      7,
      f
    );
  }
  f = message.getPhoneNumbersList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      8,
      f
    );
  }
  f = message.getBloodGroup();
  if (f !== 0.0) {
    writer.writeEnum(
      9,
      f
    );
  }
  f = message.getOfficeAddress();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      proto.hello.world.Person.Address.serializeBinaryToWriter
    );
  }
  f = message.getBirthDate();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      proto.Date.serializeBinaryToWriter
    );
  }
  f = message.getBirthTime();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      proto.myPackage.TimeStamp.serializeBinaryToWriter
    );
  }
  f = message.getLastLogin();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      proto.myPackage.DetailedDate.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.hello.world.Person.BloodGroup = {
  UNKNOWN: 0,
  A: 1,
  B: 2,
  AB: 3,
  O: 4
};




if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.hello.world.Person.Address.prototype.toObject = function(opt_includeInstance) {
  return proto.hello.world.Person.Address.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.hello.world.Person.Address} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.hello.world.Person.Address.toObject = function(includeInstance, msg) {
  var f, obj = {
    streetName: jspb.Message.getFieldWithDefault(msg, 1, ""),
    streetNumber: jspb.Message.getFieldWithDefault(msg, 2, 0),
    city: jspb.Message.getFieldWithDefault(msg, 3, ""),
    state: jspb.Message.getFieldWithDefault(msg, 4, ""),
    country: jspb.Message.getFieldWithDefault(msg, 5, ""),
    zipCode: jspb.Message.getFieldWithDefault(msg, 6, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.hello.world.Person.Address}
 */
proto.hello.world.Person.Address.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.hello.world.Person.Address;
  return proto.hello.world.Person.Address.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.hello.world.Person.Address} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.hello.world.Person.Address}
 */
proto.hello.world.Person.Address.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setStreetName(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setStreetNumber(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setCity(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setState(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setCountry(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setZipCode(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.hello.world.Person.Address.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.hello.world.Person.Address.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.hello.world.Person.Address} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.hello.world.Person.Address.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStreetName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getStreetNumber();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getCity();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getState();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getCountry();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getZipCode();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
};


/**
 * optional string street_name = 1;
 * @return {string}
 */
proto.hello.world.Person.Address.prototype.getStreetName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.hello.world.Person.Address} returns this
 */
proto.hello.world.Person.Address.prototype.setStreetName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 street_number = 2;
 * @return {number}
 */
proto.hello.world.Person.Address.prototype.getStreetNumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.hello.world.Person.Address} returns this
 */
proto.hello.world.Person.Address.prototype.setStreetNumber = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string city = 3;
 * @return {string}
 */
proto.hello.world.Person.Address.prototype.getCity = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.hello.world.Person.Address} returns this
 */
proto.hello.world.Person.Address.prototype.setCity = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string state = 4;
 * @return {string}
 */
proto.hello.world.Person.Address.prototype.getState = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.hello.world.Person.Address} returns this
 */
proto.hello.world.Person.Address.prototype.setState = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string country = 5;
 * @return {string}
 */
proto.hello.world.Person.Address.prototype.getCountry = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.hello.world.Person.Address} returns this
 */
proto.hello.world.Person.Address.prototype.setCountry = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional int32 zip_code = 6;
 * @return {number}
 */
proto.hello.world.Person.Address.prototype.getZipCode = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.hello.world.Person.Address} returns this
 */
proto.hello.world.Person.Address.prototype.setZipCode = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional int32 age = 1;
 * @return {number}
 */
proto.hello.world.Person.prototype.getAge = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.hello.world.Person} returns this
 */
proto.hello.world.Person.prototype.setAge = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.hello.world.Person.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.hello.world.Person} returns this
 */
proto.hello.world.Person.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional float height = 4;
 * @return {number}
 */
proto.hello.world.Person.prototype.getHeight = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.hello.world.Person} returns this
 */
proto.hello.world.Person.prototype.setHeight = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional double weight = 5;
 * @return {number}
 */
proto.hello.world.Person.prototype.getWeight = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.hello.world.Person} returns this
 */
proto.hello.world.Person.prototype.setWeight = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * optional bool is_married = 6;
 * @return {boolean}
 */
proto.hello.world.Person.prototype.getIsMarried = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.hello.world.Person} returns this
 */
proto.hello.world.Person.prototype.setIsMarried = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional bytes small_profile_pic = 7;
 * @return {string}
 */
proto.hello.world.Person.prototype.getSmallProfilePic = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * optional bytes small_profile_pic = 7;
 * This is a type-conversion wrapper around `getSmallProfilePic()`
 * @return {string}
 */
proto.hello.world.Person.prototype.getSmallProfilePic_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getSmallProfilePic()));
};


/**
 * optional bytes small_profile_pic = 7;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getSmallProfilePic()`
 * @return {!Uint8Array}
 */
proto.hello.world.Person.prototype.getSmallProfilePic_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getSmallProfilePic()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.hello.world.Person} returns this
 */
proto.hello.world.Person.prototype.setSmallProfilePic = function(value) {
  return jspb.Message.setProto3BytesField(this, 7, value);
};


/**
 * repeated string phone_numbers = 8;
 * @return {!Array<string>}
 */
proto.hello.world.Person.prototype.getPhoneNumbersList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 8));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.hello.world.Person} returns this
 */
proto.hello.world.Person.prototype.setPhoneNumbersList = function(value) {
  return jspb.Message.setField(this, 8, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.hello.world.Person} returns this
 */
proto.hello.world.Person.prototype.addPhoneNumbers = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 8, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.hello.world.Person} returns this
 */
proto.hello.world.Person.prototype.clearPhoneNumbersList = function() {
  return this.setPhoneNumbersList([]);
};


/**
 * optional BloodGroup blood_group = 9;
 * @return {!proto.hello.world.Person.BloodGroup}
 */
proto.hello.world.Person.prototype.getBloodGroup = function() {
  return /** @type {!proto.hello.world.Person.BloodGroup} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {!proto.hello.world.Person.BloodGroup} value
 * @return {!proto.hello.world.Person} returns this
 */
proto.hello.world.Person.prototype.setBloodGroup = function(value) {
  return jspb.Message.setProto3EnumField(this, 9, value);
};


/**
 * optional Address office_address = 10;
 * @return {?proto.hello.world.Person.Address}
 */
proto.hello.world.Person.prototype.getOfficeAddress = function() {
  return /** @type{?proto.hello.world.Person.Address} */ (
    jspb.Message.getWrapperField(this, proto.hello.world.Person.Address, 10));
};


/**
 * @param {?proto.hello.world.Person.Address|undefined} value
 * @return {!proto.hello.world.Person} returns this
*/
proto.hello.world.Person.prototype.setOfficeAddress = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.hello.world.Person} returns this
 */
proto.hello.world.Person.prototype.clearOfficeAddress = function() {
  return this.setOfficeAddress(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hello.world.Person.prototype.hasOfficeAddress = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional Date birth_date = 11;
 * @return {?proto.Date}
 */
proto.hello.world.Person.prototype.getBirthDate = function() {
  return /** @type{?proto.Date} */ (
    jspb.Message.getWrapperField(this, proto.Date, 11));
};


/**
 * @param {?proto.Date|undefined} value
 * @return {!proto.hello.world.Person} returns this
*/
proto.hello.world.Person.prototype.setBirthDate = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.hello.world.Person} returns this
 */
proto.hello.world.Person.prototype.clearBirthDate = function() {
  return this.setBirthDate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hello.world.Person.prototype.hasBirthDate = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional myPackage.TimeStamp birth_time = 12;
 * @return {?proto.myPackage.TimeStamp}
 */
proto.hello.world.Person.prototype.getBirthTime = function() {
  return /** @type{?proto.myPackage.TimeStamp} */ (
    jspb.Message.getWrapperField(this, proto.myPackage.TimeStamp, 12));
};


/**
 * @param {?proto.myPackage.TimeStamp|undefined} value
 * @return {!proto.hello.world.Person} returns this
*/
proto.hello.world.Person.prototype.setBirthTime = function(value) {
  return jspb.Message.setWrapperField(this, 12, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.hello.world.Person} returns this
 */
proto.hello.world.Person.prototype.clearBirthTime = function() {
  return this.setBirthTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hello.world.Person.prototype.hasBirthTime = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional myPackage.DetailedDate last_login = 13;
 * @return {?proto.myPackage.DetailedDate}
 */
proto.hello.world.Person.prototype.getLastLogin = function() {
  return /** @type{?proto.myPackage.DetailedDate} */ (
    jspb.Message.getWrapperField(this, proto.myPackage.DetailedDate, 13));
};


/**
 * @param {?proto.myPackage.DetailedDate|undefined} value
 * @return {!proto.hello.world.Person} returns this
*/
proto.hello.world.Person.prototype.setLastLogin = function(value) {
  return jspb.Message.setWrapperField(this, 13, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.hello.world.Person} returns this
 */
proto.hello.world.Person.prototype.clearLastLogin = function() {
  return this.setLastLogin(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hello.world.Person.prototype.hasLastLogin = function() {
  return jspb.Message.getField(this, 13) != null;
};


