apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx-deployment
# Specification for the deployment
spec:
  replicas: 0
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    # Specification of the pod that will be created.
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80