apiVersion: v1  # Kubernetes v1.7.0
kind: Service # Service is a Kubernetes resource type

# 1. Metadata for the service
metadata:
  name: nginx-service

# 2. Specification for the service
spec:
  selector: 
    app: nginx-app  # should match - Deployment Specs template.metadata.labels.app: nginx-app
  ports:
  - protocol: TCP
    port: 1234  # Port number of the service
    targetPort: 5678  # target port of the pod
  
