version: "3"
services:
  classroom-service:
    build: .      # build from Dockerfile in current directory
    container_name: classroom-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/classroom
    ports:
      - 12346:12346
    restart: always
    depends_on:
      - database
  database:
    image: postgres:latest
    container_name: database
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=classroom
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data # mount volume to persist data
    restart: always
volumes:
  pgdata:
          